<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5tag8nh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5tag8nh/appProdProjectContainer.php') {
    touch(__DIR__.'/Container5tag8nh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container5tag8nh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container5tag8nh\appProdProjectContainer(array(
    'container.build_hash' => '5tag8nh',
    'container.build_id' => '642fa7aa',
    'container.build_time' => 1539729026,
), __DIR__.\DIRECTORY_SEPARATOR.'Container5tag8nh');
